# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthenticationService2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuthenticationService2020
	pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'

  target 'AuthenticationService2020Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuthenticationService2020UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
