# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseSampleProjectMar282019' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseSampleProjectMar282019
  
  #For Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  #
  
  #For Ads
  pod 'Google-Mobile-Ads-SDK'

  target 'FirebaseSampleProjectMar282019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseSampleProjectMar282019UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
