# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConvertTextWithHTMLTagsJul3009' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConvertTextWithHTMLTagsJul3009
  pod "Atributika"

  target 'ConvertTextWithHTMLTagsJul3009Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConvertTextWithHTMLTagsJul3009UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
