# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookNewFeedStyleLoaderMar52019' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'ListPlaceholder'
  use_frameworks!

  # Pods for FacebookNewFeedStyleLoaderMar52019

  target 'FacebookNewFeedStyleLoaderMar52019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FacebookNewFeedStyleLoaderMar52019UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
