# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestingTimeZoneJul92019' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestingTimeZoneJul92019
pod "TimeZoneLocate"

  target 'TestingTimeZoneJul92019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestingTimeZoneJul92019UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
