# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Forward' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Forward
  pod 'RealmSwift'
  pod 'NVActivityIndicatorView'
  pod 'SVProgressHUD'

  target 'ForwardTests' do
    inherit! :search_paths
   
    # Pods for testing
  end

  target 'ForwardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
